insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Tomato - Plum With Basil', 'Disp fx of head of r rad, 7thQ', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Table Cloth 72x144 White', 'Nondisp fx of acromial pro, r shldr, 7thD', 'E');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Steam Pan Full Lid', 'Oth disrd of bone density and structure, shoulder', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Beef - Rib Eye Aaa', 'Pasngr in pk-up/van injured in clsn w nonmtr vehicle in traf', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Buttons', 'Toxic effect of tetrachloroethylene, assault, subs encntr', 'E');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Wine - Jafflin Bourgongone', 'Displ transverse fx shaft of l ulna, 7thD', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Pork - Inside', 'Unsp fx shaft of unsp ulna, 7thH', 'E');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Passion Fruit', 'Partial traumatic amputation of right foot, level unsp', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Pork - Bacon,back Peameal', 'Path fx in neopltc disease, pelvis, subs for fx w malunion', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Oil - Shortening,liqud, Fry', 'Subluxation of T11/T12 thoracic vertebra, subs encntr', 'E');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Tomatoes - Cherry', 'Abrasion of right front wall of thorax, initial encounter', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Cheese - Sheep Milk', 'Sltr-haris Type IV physeal fx phalanx of left toe, sequela', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Liqueur Banana, Ramazzotti', 'Contact with metalworking machines, subsequent encounter', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Tea - Mint', 'ABO incompatibility w acute hemolytic transfs react, sequela', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Mustard - Seed', 'Subluxation of tarsometatarsal joint of left foot, subs', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Snapple - Mango Maddness', 'Bitten by alligator, subsequent encounter', 'E');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Creme De Cacao White', 'Type I occipital condyle fracture, right side, 7thB', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Silicone Paper 16.5x24', 'Abnormality of plasma protein, unspecified', 'E');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Fib N9 - Prague Powder', 'Complete traumatic amputation at unsp hip joint, subs encntr', 'R');
insert into Spectacle (NameOfSpectacle, Description, AccountingSpectacle) values ('Spice - Onion Powder Granulated', 'Disease of blood and blood-forming organs, unspecified', 'E');
